### ISSUE TITLE
Segmentation fault when opening a binary?

### ISSUE THREAD

**Issue by 766F6964** [icsharpcode/AvaloniaILSpy#10]
I compiled the project from source on Manjaro 64-Bit. 
After successfully building the project I tried running the Ubuntu and the Debian build, since there is no dedicated build for arch-distros. I was able to start the application and I saw the UI etc, however when clicking on "Open..." to load a binary the application crashes with a segmentation fault without any further information.
![crash](https://user-images.githubusercontent.com/34845270/57889103-3e473f80-7834-11e9-8956-28baf652b02a.gif)

**Comment by jeffreye** [comment]
The open menu would invoke the system file dialog. Would you mind to give more details of your OS?
This is possibly a bug from X11 or Avalonia, can you try any of apps from here https://github.com/AvaloniaUI/Avalonia/wiki/Projects-that-are-using-Avalonia ?

**Comment by 766F6964** [comment]
**OS**: Linux Manjaro 
**Architecture**: 64-Bit
**Kernel**: 4.19.42-1-MANJARO
**Desktopmanager**: Gnome

I tried several other applications that are based on Avalonia and I couldn't reproduce the bug. I was told by a friend that he has the exact same problem, on a system with the same configuration.

**Comment by 766F6964** [comment]
Maybe setting up a VM with the same settings could help to recreate this issue.

**Comment by efernandesng** [comment]
I have the same issue on Arch Linux.. It's normal, the build is for Ubuntu/Debian.
The workaround is pass the target by parameter `./ILSpy target.exe`

**Comment by SecT0uch** [comment]
Same here, under Manjaro Cinnamon

**Comment by jeffreye** [comment]
@766F6964 I have set up a VM for this bug. Both ubuntu and debian version work on my VM. 
![image](https://user-images.githubusercontent.com/1737680/59073793-82e75900-887d-11e9-98cd-e342af7a346d.png)

**Comment by SecT0uch** [comment]
The issue seems to occur with Arch-based distributions only, when clicking on "Open..."

**Comment by 766F6964** [comment]
Is your VM a Manjaro VM? Try opening an assembly by using the "Open..." context menu.

**Comment by jeffreye** [comment]
yes. And it works
________________________________

**Comment by SecT0uch** [comment]
I bypassed the issue the same way. The binaries yes, but building from the sources produces the same issue.

**Comment by Washi1337** [comment]
I seem to have the same issue as OP. I am running Manjaro Gnome on this machine and tried running the precompiled binaries, as well as building the source myself.  Both result for me in a segfault.

**Comment by bkaraceylan** [comment]
Same issue on 5.1.9 kernel Arch linux running Gnome 3.32.2.

**Comment by jeffreye** [comment]
I am still unable to reproduce it. It'd be better if you can send me a .iso image file. 
![Jul-04-2019 13-36-13](https://user-images.githubusercontent.com/1737680/60687014-bf987700-9e60-11e9-8ec2-273c3fb97128.gif)

**Comment by thives** [comment]
It is caused by this https://github.com/mono/SkiaSharp/issues/927

**Comment by jeffreye** [comment]
Thanks for identifying it.
________________________________

**Comment by evaleries** [comment]
Same here for Kali Linux 2019.4

**Comment by Washi1337** [comment]
A workaround for this issue is to add a call to `UseManagedSystemDialogs()` in `Program.BuildAvaloniaApp`, as well as upgrading to Avalonia 0.9.1, and then build the solution using the `build.sh` script. Not ideal, but at least makes the application not segfault.

**Comment by jeffreye** [comment]
Good to know. I'll look into it
________________________________
