### ISSUE TITLE
7.1RC Doesn't launch on macos monterey x64

### ISSUE THREAD

**Issue by cedricbrasey** [icsharpcode/AvaloniaILSpy#107]
Hey Guys,

Sorry to say this but i've downloaded the app and extracted as directed and no joy!

![image](https://user-images.githubusercontent.com/2300497/153351384-22cc6a18-1cac-4fff-962e-7de60077ce18.png)

**Comment by jeffreye** [comment]
Check out https://github.com/icsharpcode/AvaloniaILSpy/issues/63
