### ISSUE TITLE
Bump ILSpy component to 8.0

### ISSUE THREAD

**Issue by clin1234** [icsharpcode/AvaloniaILSpy#135]
Release tag: https://github.com/icsharpcode/ILSpy/releases/tag/v8.0

**Comment by christophwille** [comment]
To add a bit color: only upgrading ics.d or ilspyx won't do the trick (although mostly). Also note that going through the RTM release notes will NOT show the entire picture as those line items are cherry-picked from the preview releases (best to read each preview release note).

**Comment by christophwille** [comment]
#142 is the minimal update to the decompilation engine. More details for how we might proceed is at https://github.com/icsharpcode/AvaloniaILSpy/issues/136#issuecomment-1651150503
