### ISSUE TITLE
Add Information About Mono Requirements Needed for Building on Linux

### ISSUE THREAD

**Issue by 7enderhead** [icsharpcode/AvaloniaILSpy#137]
- trying to build on Fedora 38 first tripped over the missing 'mono' dependency, needed to invoke nuget.exe
- installing mono was not enough, though
- I got a `Could not load file or assembly 'Microsoft.Build.Utilities.v4.0'` error
- trying to install the 'native' nuget brought the solution: package 'mono-devel' is also needed

**Comment by christophwille** [comment]
Was that for using build.sh or building the .sln inside eg VSCode? (Note that I just completed #139)

**Comment by 7enderhead** [comment]
This was for building with build.sh.

**Comment by christophwille** [comment]
Ok, so this can be closed as build.* has been removed in the process of upgrading to Cake-latest.
