### ISSUE TITLE
Builds fail to download

### ISSUE THREAD

**Issue by derekforeman** [icsharpcode/AvaloniaILSpy#18]
Looks like the windows and osx builds are not available from the links.

**Comment by christophwille** [comment]
Are you referring to https://github.com/icsharpcode/AvaloniaILSpy/releases/tag/v4.0-rc2 ?

**Comment by derekforeman** [comment]
that helps out! I was referring to the links on the main repo page. 
![Screen Shot 2019-10-11 at 8 41 26 AM](https://user-images.githubusercontent.com/566610/66652151-f7068480-ec02-11e9-8f45-520fbfd07992.png)

**Comment by christophwille** [comment]
I'll keep that open because in README.md the links are wrong.

**Comment by jeffreye** [comment]
Fixed
