### ISSUE TITLE
Run fails with "No usable version of the libssl was found" on Ubuntu >19.04

### ISSUE THREAD

**Issue by berkes** [icsharpcode/AvaloniaILSpy#19]
Ubuntu 19.04 comes with openssl1.1, which is not compatible with openssl1.0. 

Download and building openssl1.0 manually in  /usr/local/ssl (the default ssl location for manual builds) does not resolve this issue. Somehow ILSpy does no pick up this library. Or the problem is elsewhere.

Also reported in the library used: https://github.com/dotnet/corefx/issues/31709

I assume this is the issue here.

**Comment by christophwille** [comment]
@berkes please try the latest from the releases tab. Maybe the newer Avalonia version fixes this.

**Comment by berkes** [comment]
I no longer need this, so I don't have the libs and to-extract binaries anymore. 

For me, this can be closed.
