### ISSUE TITLE
File -> Open button is disabled

### ISSUE THREAD

**Issue by JeremyWildsmith** [icsharpcode/AvaloniaILSpy#21]
Hello,

When I try to open an assembly via File -> Open, the "Open" menu option is grayed out. There is no error message, so I am not sure where to go from here.

I am using the latest build on Linux Ubuntu Version 18.04.2 LTS

Any advice?

Thanks!

**Comment by jeffreye** [comment]
I'm working on a fix. You could use key shortcut as workaround ( Ctrl+ O)
