### ISSUE TITLE
"Images" directory casing on unix-like systems leaves some icons unfound

### ISSUE THREAD

**Issue by Washi1337** [icsharpcode/AvaloniaILSpy#25]
**Summary:**
The artifacts produced by `build.sh` contain a directory called `Images`, but AvaloniaILSpy sometimes references the directory `images` instead. This is a problem on operating systems such as Linux, where file paths are case sensitive.

**How to reproduce:**
- Use any Linux operating system (I tested it on Manjaro x64)
- Use `build.sh` to build AvaloniaILSpy.
- Navigate to `artifacts/linux_x64` and run `./ILSpy`.
- Open any binary and e.g. right click on a type in the assembly explorer tree view.
- Observe AvaloniaILSpy crashing with the following the error in the terminal:
```
Sorry, we crashed
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/washi/Documents/Programming/AvaloniaILSpy/artifacts/linux-x64/images/SearchMsdn.png'.
```

**Full log:**
https://pastebin.com/z5L1gUpW

**Comment by jeffreye** [comment]
#24 should fix this
