### ISSUE TITLE
Upgrade Avalonia

### ISSUE THREAD

**Issue by mausch** [icsharpcode/AvaloniaILSpy#33]
Hi and thank you for all your hard work on this project!
I'm getting a NullReferenceException running ILSpy on NixOS. 
This is a well-known issue that has affected e.g. https://github.com/zkSNACKs/WalletWasabi/issues/2856 .
Avalonia has already been patched to fix this bug in 0.9.2 ( https://github.com/AvaloniaUI/Avalonia/pull/3453 ).
Now all that remains to do in this project is updating Avalonia. It seems that this is actually defined in AvaloniaEdit? ( https://github.com/jeffreye/AvaloniaEdit/blob/AvaloniaILSpy/build.cake#L158 ) so currently 0.9.0-preview1 .
I noticed this project uses a fork of AvaloniaEdit? No idea about that tbh. Possibly related to https://github.com/icsharpcode/AvaloniaILSpy/issues/31
I've also filed an issue on the original AvaloniaEdit to upgrade https://github.com/AvaloniaUI/AvaloniaEdit/issues/101

**Comment by jeffreye** [comment]
Hi,
Thanks for finding this issue. I wasn't aware of the version defined in cake file but this project is unlikely getting affected.
We use AvaloniaEdit as a subproject as the artifact in NuGet isn't update to date. 
https://github.com/icsharpcode/AvaloniaILSpy/blob/c9191f3b5bc417655dd4e1e5c48de351d7f0c6e4/ILSpy.sln#L17

**Comment by christophwille** [comment]
@mausch can you please test the latest release? It sports Avalonia .9.9 and upstream AvaloniaEdit.

**Comment by mausch** [comment]
Works great now, thanks!
