### ISSUE TITLE
[mac] 'The application ILSpy can't be opened' error on launch

### ISSUE THREAD

**Issue by gsgou** [icsharpcode/AvaloniaILSpy#42]
Workaround it with
chmod +x "/Applications/ILSpy.app/Contents/MacOS/ILSpy"

**Comment by vodiylik** [comment]
same problem

**Comment by eAi** [comment]
Same problem here too - workaround worked though. Would distributing as a DMG help?

**Comment by jeffreye** [comment]
@eAi it compiled in a windows server (azure) , chmod might not work there. This is likely the root cause.

**Comment by jijiechen** [comment]
It helped, thanks a lot.

To help people searching, in my case, the error message was "You do not have permission to open ILSpy, contact Your computer or network Administrator for assistance."

**Comment by ricsirigu** [comment]
I am facing the same issue, and unfortunately the workaround doesn't work in my case :(
I have Monterey on a MacBook with the M1. 
I tried both the arm64 and the x64 releases with no luck

**Comment by jeffreye** [comment]
Please have a look at https://github.com/icsharpcode/AvaloniaILSpy/issues/63 too

**Comment by ricsirigu** [comment]
> Please have a look at #63 too

Thanks, it worked with `xattr -rd com.apple.quarantine /Applications/ILSpy.app`
