### ISSUE TITLE
Build.sh fails

### ISSUE THREAD

**Issue by Shiva108** [icsharpcode/AvaloniaILSpy#45]
With error: 
An error occurred when executing task 'Restore-NetCore'.
Error: One or more errors occurred. (.NET Core CLI: Could not locate executable.)
	.NET Core CLI: Could not locate executable.

On linux: Linux parrot 5.9.0-2parrot1-amd64 #1 SMP Debian 5.9.6-2parrot1 (2020-11-17) x86_64 GNU/Linux

**Comment by jeffreye** [comment]
Did you `dotnet` to your PATH?

**Comment by christophwille** [comment]
No more feedback provided, closing.

**Comment by Attributus** [comment]
Thank you for the dotnet to path piece. I ran into the same issue and found that the initial install of dotnet had not worked due to the prompt for using additional space being entered incorrectly. After installing correctly and having the correct path it worked!
