### ISSUE TITLE
So I am trying to decompile a unity games DLL on Mac. ILSpy just keeps crashing though.

### ISSUE THREAD

**Issue by StupidRepo** [icsharpcode/AvaloniaILSpy#47]
So I am on Mac, trying to open a DLL file of a unity game which works but sometimes it crashes on Decompiling and most of the time it crashes when opening it up and pressing on a class(?).

Please fix this :/

**Comment by siegfriedpammer** [comment]
Please provide more information on the details of the crash.

**Comment by gideongrinberg** [comment]
@siegfriedpammer I'm getting the same error on MacOS Catalina when I try to export anything. Please let me know what ohter details you need.

**Comment by siegfriedpammer** [comment]
Would be interesting to see the details of the crash. Do you have a stack trace or similar? Thanks!

**Comment by gideongrinberg** [comment]
> Would be interesting to see the details of the crash. Do you have a stack trace or similar? Thanks!

Thanks for the response! I don't have one, and I'm not actually sure how to get one 😄

**Comment by christophwille** [comment]
No more feedback provided, closing.
