### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by andrfgs** [icsharpcode/AvaloniaILSpy#49]
So I have ran the build as instructed:
1. `git clone --recurse-submodules https://github.com/icsharpcode/AvaloniaILSpy.git`
2. `./build.sh`

And build fails with the following error:
```
/usr/share/dotnet/sdk/5.0.102/NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/symreader-converter/api/v3/index.json. [/home/andre/AvaloniaILSpy/ILSpy/ILSpy.csproj]
/usr/share/dotnet/sdk/5.0.102/NuGet.targets(131,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/home/andre/AvaloniaILSpy/ILSpy/ILSpy.csproj]
An error occurred when executing task 'Restore-NetCore'.
Error: One or more errors occurred. (.NET Core CLI: Process returned an error (exit code 1).)
        .NET Core CLI: Process returned an error (exit code 1).
```

So I checked `https://dotnet.myget.org/F/symreader-converter/api/v3/index.json` and it really doesn't exist. So apparently the feeds have expired. Anyone knows how to fix this?

**Comment by christophwille** [comment]
https://github.com/icsharpcode/ILSpy/commit/4307125df12e34859f720ef497e77c4b34d8de32 (if the tests are copied too, then also https://github.com/icsharpcode/ILSpy/commit/08de8416f5de0fdeb779ddd5c20d7a635608e75f)

**Comment by andrfgs** [comment]
@christophwille I can't thank you enough for this. The fix in commit `4307125` solves this problem.

To fix it for this repo, someone just needs to edit the file `nuget.config` and replace line:
`<add key="DotNet MyGet" value="https://dotnet.myget.org/F/symreader-converter/api/v3/index.json" />`

with:
<add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />

I'll leave the issue open since this needs to be fixed in the repo as well. Once again thanks a lot for the help @christophwille

**Comment by Necklaces** [comment]
@christophwille Thanks for this fix! Are you able (and willing) to make a RC3 release as well, seeing as the RC2 build is broken because of this issue?

**Comment by christophwille** [comment]
Why would a past release be broken because of this?

**Comment by Necklaces** [comment]
@christophwille By cloning the repository and building from the RC2 git tag, the AUR package does this for reproducibility.

**Comment by christophwille** [comment]
I don't know how far along @jeffreye is with Avalonia 0.10 adaptations - I don't want to mess with his release strategy.

**Comment by Necklaces** [comment]
That's alright, no worries. We can wait for that then.

Actually, come to think of it, maybe there's a way to backport this fix to that release?
