### ISSUE TITLE
add ARM64

### ISSUE THREAD

**Issue by iMonZ** [icsharpcode/AvaloniaILSpy#50]
Please add an arm64 build for linux and macOS

**Comment by christophwille** [comment]
How would we verify that? I only have a Windows Surface X, and my MBP is 2015 Intel. Without actual HW on our end this is going to be a very brittle release.

**Comment by iMonZ** [comment]
> How would we verify that? I only have a Windows Surface X, and my MBP is 2015 Intel. Without actual HW on our end this is going to be a very brittle release.

Hey,
I have an arm64 MacBook and arm64 Linux device :)

**Comment by iMonZ** [comment]
> > How would we verify that? I only have a Windows Surface X, and my MBP is 2015 Intel. Without actual HW on our end this is going to be a very brittle release.
> 
> Hey,
> I have an arm64 MacBook and arm64 Linux device :)

I would like to help it myself but your build system is not compatible with my system (visual studio)

**Comment by iMonZ** [comment]
> How would we verify that? I only have a Windows Surface X, and my MBP is 2015 Intel. Without actual HW on our end this is going to be a very brittle release.

Hey,
the macOS build SDK is 10.13 do you know where this is defined or how to change this?

**Comment by christophwille** [comment]
I don't think we are doing anything with macOS SDKs, that must be implicit through either .NET Core or maybe Avalonia?

**Comment by christophwille** [comment]
Oh, right, Scott Hunter mentioned M1 + .NET 5 RTM too close together during his Ignite talk.

**Comment by iMonZ** [comment]
This issue is going to be continued here: #56
