### ISSUE TITLE
Cross-platform build

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/AvaloniaILSpy#55]
@jeffreye  https://github.com/icsharpcode/AvaloniaILSpy/blob/master/build.cake#L5 is this still needed? Obviously wouldn't be x-plat.

https://github.com/icsharpcode/AvaloniaILSpy/pull/53#issuecomment-782740324 maybe a build matrix but ubuntu might be sufficient. Question is: are x permissions on the build output in the first place?

**Comment by christophwille** [comment]
Would a dotnet build & dotnet publish suffice? (ie is cake "overkill"?)

**Comment by jeffreye** [comment]
Need special treatments for osx. I don't see `dotnet` provides such feature to create app bundle for osx.

**Comment by christophwille** [comment]
Valid argument. Ok, so we keep cake.

**Comment by christophwille** [comment]
.cake has been fixed, matrix build is active.

**Comment by iMonZ** [comment]
> Need special treatments for osx. I don't see `dotnet` provides such feature to create app bundle for osx.

Maybe this could help?
https://avaloniaui.net/docs/packing/macOS
