### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by christophwille** [icsharpcode/AvaloniaILSpy#83]
See https://github.com/actions/virtual-environments/issues/2187

We need GitHub Actions support (local building https://github.com/icsharpcode/AvaloniaILSpy/blob/master/ILSpy/ILSpy.csproj#L10 needs to be adjusted, but first #82 needs to be merged because M1 support is in .NET 6.0)

**Comment by jeffreye** [comment]
I just ordered a M1 MacBook, I'll pick this up next month

**Comment by christophwille** [comment]
I too should get an MBA soon for testing; could you take a look at #82 before? Should be innocous enough (binaries work nicely on Windows)

**Comment by AraHaan** [comment]
I have a 64 bit macbook pro from 2015 I can test it on.

**Comment by AraHaan** [comment]
And it works on my Mac. 👌

**Comment by christophwille** [comment]
I have merged my PR #82 - I got my MBA M1 for testing now.

**Comment by christophwille** [comment]
I added the RID "osx-arm64" - that didn't change a thing; then in ILSpy.csproj I started adding SkiaSharp to override Avalonia's default version - each version https://www.nuget.org/packages/SkiaSharp/ gave a more detailled error message until I hit the one for libHarfBuzzSharp on version 2.88.0-preview.155 which seems to have been reported on SkiaSharp repo:

https://github.com/mono/SkiaSharp/issues/1829

Given that I am not an expert on any of those things (code signing on Apple, Skia or Avalonia) this is the beginning of investigations for somebody else.
